language: go
go:
- 1.x
before_script:
- go get github.com/imdario/mergo
script:
- CGO_ENABLED=0 go build -gccgoflags "-s" && GOOS=windows GOARCH=amd64 go build -gccgoflags "-s"
deploy:
  provider: releases
  api_key:
    secure: "QsGlX0JW0oH7b1ACsqzP04pMfu4xk5+kr577titmrkoEcE3VzFCjStlKhKcwox1wmchPtCrzzS8wt1LhRoqTbnUvhcWv02ngZX7Pr2BpE3pqF5bRMoxs1mQ3m10mIc5+JGmuFj96VokWHBxrcAn5YCODijqBTFxFhBNaTUVx4ma8RHy9PNdBCTKtc4CD8bV16qdHjrVf6vFRPB16uThRN0axKw6ZybPeEYBiDtKQU9YwlST5MVOWVkjMP16gI2hfUT8woiN8tJwcMu0elEvLIEgMOHmpKuwsSPJ6t2a4uBSANtrMFL8CJ/3lzanw93NJgV6QcEQCEx9CkYKF0FSGXDjFI0YLdzsuRt/Lsi6/uyhCsd5CrDJWSHKxVci2PlE6OFeVsKZw17G2Z3yEgZtAEI+do5slgwT63HZGsTv/d08g4M+0M5F0CHs498YQ9IzlDcLCWsWs80jjQSX8IfefCvzeEjTtDiTIt8+rhm3RdtoI6YbbRuLtGJWfeg8Nq8Vg2Fy5E6p5C7Pb2Gs9PLB4Wo/yG5mkpajMKPCOn35sWWY193tep1uV6KKJQU8usIaCfrGJ9et9lTC/vMhFl29ttOsR2/03LebwmJdGMj3GLZAK2SKnEZY9XXL2j1gIqGfl7f3CQnWyLJFvZY8pfnAC4hVCWC5I9yhR+iuTJpAI/Z4="
  file:
    - gotemplated
    - gotemplated.exe
  overwrite: true
  skip_cleanup: true
  on:
    tags: true