language: go
go:
- 1.x
before_script:
- go get github.com/imdario/mergo
script:
- CGO_ENABLED=0 go build -gccgoflags "-s" && GOOS=windows GOARCH=amd64 go build -gccgoflags "-s"
deploy:
  provider: releases
  api_key:
    secure: "lawU3vUSsspzFAndFJvMIvuXuB1SVV0oP22KReACUGD0MZ+8u7phytEIqify6yp4FNSNDeUb4fPbLUAhjY0pd/ZBLmEPlvwzKp/ciwrKgSvTZvmKrkXrXqggwK7+BiwXmRbHEH24ISpj2uPXSB1p9sTIjseEqjXIRDjoAFcDZsesEeu2k3NuBNX4G9ss8OS/3S8+ywepk4moKP+8dDrZ/Sz+GVfI3t37bwNQxcELfxMyrZmaEswfl//E7liQ+UxVsYalSm0EF89tnUnfeAiMiRK7e6n8q+CWPiubB7oUWeKoAbxqss5P4760sVo6WKXI5smVaNzlx46T8E91e0rDJUZXdMhgzHP4mv1LRagfUPlM2g4qRefjZwIZCYmkOw6skuyJzw/SSDSoXOllXcjsYzS8ofpcoJUTcHhOJV3vZWVv8KLsLnODeRTHRqZzJbTCnxKWsMaYT1hBCUlJwSTUoaxsXhfUff/GLn3AhTerpHpbtvd3a2Uct79etitJstyl+Bx09uu2BF1B9U0ozw9hWk+aLIQKIDym3XKKEPao/GPzj6cfY5yWcO/vRR+nNjBrfS6M+OQ4cpNve2quk1DADLfnOwxvFH4UYidt/ZRskWi4eMJcDHKAVCCK1GDhA5T50U8rjVw1Q4YLxlJ+mqfpVtMOeJ4/gurXwTFuBgps24c="
  file:
    - gotemplated
    - gotemplated.exe
  overwrite: true
  skip_cleanup: true
  on:
    tags: true